### ISSUE TITLE
Two sequeces?

### ISSUE THREAD

**Issue by arturser** [co11ter/goFAST#2]
I have problem to encode template with two sequences? Is it possible?

**Comment by co11ter** [comment]
If you have a problem with two sequence, that will be bug. What kind of problem have you got? Please, show your template and data .

**Comment by arturser** [comment]
Template is this one:
<template name="MarketDataRequest" id="59" xmlns="http://www.fixprotocol.org/ns/fast/td/1.1">
*********
******   irrelevant "normal" fields which works OK.
**********
    <sequence name="MDEntries">
      <length name="NoMDEntryTypes" id="267" />
      <string name="MDEntryType" id="269">
        <default value="2" />
      </string>
    </sequence>
    <sequence name="Instruments">
      <length name="NoRelatedSym" id="146">
      </length>
      <string name="Symbol" id="55">
      </string>
      <uInt32 name="MaturityMonthYear" id="200" presence="optional">
      </uInt32>
      <decimal name="StrikePrice" id="202" presence="optional">
      </decimal>
      <string name="SecurityExchange" id="207" presence="optional">
      </string>
      <string name="CFICode" id="431">
      </string>
    </sequence>
  </template>
I attached file where I tried my best to explain what I have and where is problem tougether with full template from GAIN Capital.
[sequences.docx](https://github.com/co11ter/goFAST/files/4194655/sequences.docx)

**Comment by arturser** [comment]
Alexander! Might be in some help would be GAIN official documentation (FAST is closer to end):
https://gainfutures.com/GFAPI/#

**Comment by co11ter** [comment]
I've fixed some bug related to multisequence. @arturser, can you check your case?
