### ISSUE TITLE
No API to check for field's presence

### ISSUE THREAD

**Issue by vvoznesensky** [co11ter/goFAST#3]
Hi there.

There seems to be no interface to check if some field is present or absent in a message.

How to understand if some optional scalar field is omitted?

Thanks in advance.

**Comment by co11ter** [comment]
Hi! 

You can use pointer like there: https://github.com/co11ter/goFAST/blob/b9b6ceb6c733fec4f6b2f904bf8970023fd3f31c/example_test.go#L41

Also, you can check `field.Value` is nil or not: https://github.com/co11ter/goFAST/blob/master/example_decoder_test.go#L71

**Comment by vvoznesensky** [comment]
Thank you
