### ISSUE TITLE
Generating code from XML definition

### ISSUE THREAD

**Issue by vvoznesensky** [co11ter/goFAST#4]
Hello again.

What about generating go code from XML schema definition?

I'd like to implement such a generator, but need some coaching.

**Comment by co11ter** [comment]
What is the reason for that?

**Comment by vvoznesensky** [comment]
The main rationale is to avoid repeating definition of structs.

For instance, Google Protobuf has such code generators for many languages.

**Comment by co11ter** [comment]
It is possible outside of this library...

**Comment by vvoznesensky** [comment]
Ok, I would inform you if I'll start such a generator.
